"""Phantom-order fill labelling pipeline for the competitive NN benchmark.

Replays the historical event stream of an empirical KGHM SQLite database
and, at each chosen timestamp ``t``, simulates a phantom limit order at
every legal resting price tick inside the configured delta bounds.  Delta
is derived from that executable price and the exact BBO midpoint, so its
parity naturally follows the spread (whole-tick or half-tick offsets).
The merged ``orders + mo_orders`` stream is walked forward to ``t + tau``,
updating a per-candidate ``queue_ahead`` tracker as cancellations and new
same-side LOs ahead of the phantom occur.

The phantom is treated as **invisible** to the market: real cancellations
and new LOs in ``(t, t + tau]`` are applied unchanged even though some
might not have occurred had the phantom really been there.  The fill
predicate is ``mo_volume >= queue_ahead + phantom_size``.

Queue-position semantics (price-time priority):

- At placement, the queue ahead includes all same-side depth at prices
  strictly more aggressive than the phantom and, at the phantom's exact
  price, all then-existing depth (price-time priority — phantom placed
  *now* sits behind anything that existed before).
- During ``(t, t + tau]``, a same-side LO is added to ``queue_ahead``
  only if its price is **strictly** more aggressive than the phantom.
  A same-price LO is queued behind us → no change.
- A same-side CXL decrements ``queue_ahead`` only if cancelled at a
  price strictly more aggressive than the phantom.  Same-price CXLs are
  ambiguous (could be removing an "ahead" or a "behind" order) and are
  ignored.  This is conservative: keeps ``queue_ahead`` larger and so
  biases the labels slightly toward "no fill".

The output schema and downstream usage are documented in
``data/phantom_labels/README.md`` (generated by the CLI runner
``scripts/build_phantom_labels.py``).
"""

from __future__ import annotations

import json
import math
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional, Tuple, Union

import numpy as np
import pandas as pd

from .hawkes_filter import (
    DEFAULT_LABELS,
    HawkesFilter,
    HawkesFilterFactory,
    classify_event,
    classify_mo,
    resolve_filter_factory,
)
from .helpers import resolve_data_path


# --- Hawkes dimension shortcuts ---
# Matches DEFAULT_LABELS = ("MO_bid", "MO_ask", "LO_bid", "LO_ask",
#                          "CXL_bid", "CXL_ask")
DIM_MO_BUY = 0    # aggressive buy MO (walks asks); fills our resting ask
DIM_MO_SELL = 1   # aggressive sell MO (walks bids); fills our resting bid
DIM_LO_BID = 2
DIM_LO_ASK = 3
DIM_CXL_BID = 4
DIM_CXL_ASK = 5


# --- Feature schema ---


def build_delta_grid(
    tick_size: float, max_delta: float, delta_lo: float,
) -> np.ndarray:
    """Return the half-tick support possible across all legal BBO midpoints."""
    step = float(tick_size)
    lo = float(delta_lo)
    hi = float(max_delta)
    if not math.isfinite(step) or step <= 0.0:
        raise ValueError("tick_size must be positive")
    if not (math.isfinite(lo) and math.isfinite(hi)) or hi < lo:
        raise ValueError("max_delta must be finite and >= delta_lo")
    index_lo = int(math.ceil(lo / step - 1e-9))
    index_hi = int(math.floor(hi / step + 1e-9))
    if index_hi < index_lo:
        return np.empty(0, dtype=np.float64)
    return step * np.arange(index_lo, index_hi + 1, dtype=np.float64)


INVALID_PRICE_TICK = np.iinfo(np.int64).min


def _price_to_tick_index(price: float, tick_size: float) -> int:
    """Convert an executable price to its integer tick index."""
    price_value = float(price)
    tick = float(tick_size)
    if not math.isfinite(tick) or tick <= 0.0:
        raise ValueError("tick_size must be positive")
    if not math.isfinite(price_value):
        raise ValueError(f"price must be finite, got {price!r}")
    scaled = price_value / tick
    nearest = int(round(scaled))
    if not math.isclose(
        scaled, nearest, rel_tol=0.0, abs_tol=1e-6,
    ):
        raise ValueError(
            f"price {price!r} is not aligned to tick_size={tick_size!r}"
        )
    return nearest


def _prices_to_tick_indices(
    prices: np.ndarray, tick_size: float,
) -> np.ndarray:
    """Vectorised price-to-tick conversion; non-finite prices use a sentinel."""
    tick = float(tick_size)
    if not math.isfinite(tick) or tick <= 0.0:
        raise ValueError("tick_size must be positive")
    values = np.asarray(prices, dtype=np.float64)
    out = np.full(values.shape, INVALID_PRICE_TICK, dtype=np.int64)
    finite = np.isfinite(values)
    if not finite.any():
        return out
    scaled = values[finite] / tick
    nearest = np.rint(scaled)
    aligned = np.isclose(scaled, nearest, rtol=0.0, atol=1e-6)
    if not aligned.all():
        bad = values[finite][~aligned][:5]
        raise ValueError(
            f"found off-tick order prices for tick_size={tick_size}: "
            f"{bad.tolist()}"
        )
    out[finite] = nearest.astype(np.int64)
    return out


def build_legal_tick_state(
    best_bid: float,
    best_ask: float,
    bid_depth: np.ndarray,
    ask_depth: np.ndarray,
    side: int,
    *,
    tick_size: float,
    delta_lo: float,
    max_delta: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return legal phantom prices, mid-relative deltas, and queue ahead.

    Candidate prices are integer market ticks and cannot cross the opposite
    BBO.  Delta is represented internally in half-ticks because the midpoint
    of two legal prices can lie halfway between ticks.
    """
    tick = float(tick_size)
    if not math.isfinite(tick) or tick <= 0.0:
        raise ValueError("tick_size must be positive")
    if float(max_delta) < float(delta_lo):
        raise ValueError("max_delta must be >= delta_lo")
    if side not in (1, 2):
        raise ValueError(f"side must be 1 (bid) or 2 (ask), got {side!r}")

    bid_tick = _price_to_tick_index(best_bid, tick)
    ask_tick = _price_to_tick_index(best_ask, tick)
    if ask_tick <= bid_tick:
        raise ValueError(
            f"invalid BBO: best_bid={best_bid!r}, best_ask={best_ask!r}"
        )

    midpoint_2ticks = bid_tick + ask_tick
    half_tick = tick / 2.0
    delta_2ticks_lo = int(math.ceil(float(delta_lo) / half_tick - 1e-9))
    delta_2ticks_hi = int(math.floor(float(max_delta) / half_tick + 1e-9))

    def ceil_div2(value: int) -> int:
        return -((-value) // 2)

    if side == 1:
        price_tick_lo = max(
            1, ceil_div2(midpoint_2ticks - delta_2ticks_hi),
        )
        price_tick_hi = min(
            ask_tick - 1,
            (midpoint_2ticks - delta_2ticks_lo) // 2,
        )
    else:
        price_tick_lo = max(
            1,
            bid_tick + 1,
            ceil_div2(midpoint_2ticks + delta_2ticks_lo),
        )
        price_tick_hi = (midpoint_2ticks + delta_2ticks_hi) // 2

    if price_tick_hi < price_tick_lo:
        empty = np.empty(0, dtype=np.float64)
        return empty, empty.copy(), empty.copy()

    if side == 1:
        price_ticks = np.arange(
            price_tick_hi, price_tick_lo - 1, -1, dtype=np.int64,
        )
        delta_2ticks = midpoint_2ticks - 2 * price_ticks
        cumulative_depth = np.concatenate(
            ([0.0], np.cumsum(np.asarray(bid_depth, dtype=np.float64))),
        )
        depth_level = bid_tick - price_ticks
    else:
        price_ticks = np.arange(
            price_tick_lo, price_tick_hi + 1, dtype=np.int64,
        )
        delta_2ticks = 2 * price_ticks - midpoint_2ticks
        cumulative_depth = np.concatenate(
            ([0.0], np.cumsum(np.asarray(ask_depth, dtype=np.float64))),
        )
        depth_level = price_ticks - ask_tick

    queue_index = np.clip(
        depth_level + 1, 0, cumulative_depth.shape[0] - 1,
    )
    prices = price_ticks.astype(np.float64) * tick
    deltas = delta_2ticks.astype(np.float64) * half_tick
    queue_ahead = cumulative_depth[queue_index]
    return prices, deltas, queue_ahead


def build_feature_names(n_kernels: int, n_levels: int) -> List[str]:
    """Named columns for the per-``t`` feature vector, in stable order.

    For ``n_kernels == 1``, only the six total Hawkes intensities are kept;
    per-kernel rows would duplicate ``λ = μ +`` that single excitation row
    (up to clipping).  For ``n_kernels > 1``, ``hawkes_kernel{k}_*`` columns
    are included so time-scale decomposition is preserved.
    """
    names: List[str] = []
    # Hawkes intensity per dimension (6)
    for lbl in DEFAULT_LABELS:
        names.append(f"hawkes_intensity_{lbl}")
    # Per-kernel decomposition (n_kernels * 6); omitted when K == 1
    if n_kernels > 1:
        for k in range(n_kernels):
            for lbl in DEFAULT_LABELS:
                names.append(f"hawkes_kernel{k}_{lbl}")
    # Book depth (2 * n_levels)
    for i in range(n_levels):
        names.append(f"bid_depth_L{i}")
    for i in range(n_levels):
        names.append(f"ask_depth_L{i}")
    # Scalar features
    names.extend(["spread_ticks", "l0_imbalance", "recent_vol", "tod_frac"])
    return names


# Default book depth levels used as NN features (L0 .. L{n-1}).
PHANTOM_DEFAULT_N_BOOK_LEVELS = 10
# Default depth levels used for queue_ahead computation in labelling.
PHANTOM_DEFAULT_N_QUEUE_LEVELS = 40
# Export tuple for docs / smoke tests: single kernel + default depth count
# (no hawkes_kernel* columns when K == 1).
PHANTOM_PER_T_FEATURES: Tuple[str, ...] = tuple(
    build_feature_names(1, PHANTOM_DEFAULT_N_BOOK_LEVELS)
)


# --- Volatility feature ---


def realized_vol_time_grid(
    t_sec: np.ndarray,
    mid: np.ndarray,
    window_s: float = 200.0,
    sample_dt_s: float = 1.0,
    floor: float = 1e-8,
) -> np.ndarray:
    """Cadence-independent trailing realised volatility, aligned to inputs.

    The mid series is resampled onto a uniform ``sample_dt_s`` grid spanning
    ``[t_sec[0], t_sec[-1]]`` via last-observation-carried-forward.  Realised
    volatility at a grid point is the RMS of the log-mid returns over the
    trailing ``window_s`` seconds (i.e. the last ``round(window_s/sample_dt_s)``
    grid returns).  Each input row ``i`` is then assigned the realised vol of
    the grid cell containing ``t_sec[i]``, so the result is aligned 1:1 with the
    input arrays and is independent of the event cadence of ``t_sec``/``mid``.

    Parameters
    ----------
    t_sec : np.ndarray
        Per-row timestamps in seconds (monotonic non-decreasing).
    mid : np.ndarray
        Per-row mid prices (same length as ``t_sec``).
    window_s : float
        Trailing window length in seconds (default 200).
    sample_dt_s : float
        Grid spacing in seconds (default 1).
    floor : float
        Variance floor (the returned vol is ``>= sqrt(floor)``).

    Returns
    -------
    np.ndarray
        Realised vol per input row, shape ``(len(t_sec),)``.
    """
    n = int(t_sec.shape[0])
    out = np.full(n, math.sqrt(floor), dtype=np.float64)
    if n == 0:
        return out
    dt = float(sample_dt_s)
    if dt <= 0:
        raise ValueError("sample_dt_s must be positive")
    t0 = float(t_sec[0])
    span = float(t_sec[-1]) - t0
    if not np.isfinite(span) or span < dt:
        return out  # too short for a single grid return -> floor everywhere

    n_win = max(1, int(round(float(window_s) / dt)))
    n_grid = int(math.floor(span / dt))  # grid points 1..n_grid (0 is t0)
    grid_t = t0 + dt * np.arange(n_grid + 1, dtype=np.float64)

    # LOCF resample: mid at the last input row with t_sec <= grid time.
    pos = np.searchsorted(t_sec, grid_t, side="right") - 1
    np.clip(pos, 0, n - 1, out=pos)
    grid_mid = np.asarray(mid, dtype=np.float64)[pos]

    valid = (grid_mid > 0) & np.isfinite(grid_mid)
    with np.errstate(divide="ignore", invalid="ignore"):
        ret = np.log(grid_mid[1:] / grid_mid[:-1])
    ret = np.where(valid[1:] & valid[:-1], ret, 0.0)
    r2 = ret * ret

    # Trailing-window mean of squared returns via cumulative sums.
    csum = np.concatenate(([0.0], np.cumsum(r2)))  # len n_grid + 1
    k = np.arange(n_grid + 1)
    lo = np.maximum(0, k - n_win)
    cnt = np.maximum(k - lo, 1)
    meansq = (csum[k] - csum[lo]) / cnt
    var = np.maximum(meansq, floor)
    var[0] = floor
    vol_grid = np.sqrt(var)

    # Map each input row to its grid cell.
    cell = np.floor((t_sec.astype(np.float64) - t0) / dt).astype(np.int64)
    np.clip(cell, 0, n_grid, out=cell)
    return vol_grid[cell]


# --- Configuration ---


@dataclass
class PhantomLabelConfig:
    """Tunable parameters for :class:`PhantomLabeller`."""

    tau: float = 1.0
    """Phantom horizon in seconds."""

    delta_lo: float = -0.50
    """Lower bound (PLN) for mid-relative candidate deltas."""

    max_delta: float = 2.0
    """Upper bound (PLN) for mid-relative candidate deltas."""

    tick_size: float = 0.05
    """Executable market-price increment in PLN."""

    grid_mode: str = "legal_price_ticks"
    """Candidate construction. ``legal_price_ticks`` emits only executable
    absolute prices; ``uniform`` reproduces the historical midpoint-relative
    delta grid used by the profitable simulation pipeline."""

    phantom_size: int = 1
    """Size (shares) of the hypothetical limit order."""

    cadence: str = "bbo_change"
    """Labelling cadence.  ``bbo_change`` (default), ``every_event``, or
    ``fixed_dt:<seconds>``."""

    vol_mode: str = "ewma_event"
    """Realised-volatility feature definition.  ``ewma_event`` (default,
    legacy) is an EWMA of squared log-mid returns indexed per *event*, so its
    scale depends on event cadence.  ``realized_time`` is the cadence-independent
    trailing realised vol on a uniform time grid (see ``vol_window_s`` /
    ``vol_sample_dt_s``) — use this when the labelled cadence (e.g. simulated
    order flow) differs from the rate the feature is reconstructed at inference."""

    vol_halflife: int = 50
    """Half-life (in events) for the EWMA realised-volatility feature
    (``vol_mode='ewma_event'`` only)."""

    vol_window_s: float = 200.0
    """Trailing window (seconds) for ``vol_mode='realized_time'``: realised vol
    is the RMS of log-mid returns sampled on the grid over the last
    ``vol_window_s`` seconds."""

    vol_sample_dt_s: float = 1.0
    """Grid spacing (seconds) for ``vol_mode='realized_time'``.  Defaults give
    200 evenly-spaced 1 s return samples."""

    session_start_hhmm: str = "09:00"
    """Local-time session open for the time-of-day feature."""

    session_end_hhmm: str = "17:00"
    """Local-time session close for the time-of-day feature."""

    n_book_levels: int = PHANTOM_DEFAULT_N_BOOK_LEVELS
    """Same-side depth levels used as NN features (``bid_depth_L0`` …)."""

    n_queue_levels: int = PHANTOM_DEFAULT_N_QUEUE_LEVELS
    """Same-side depth levels loaded from SQLite for ``queue_ahead``
    computation in ``_initial_state``.  Must be >= ``n_book_levels`` and
    match the extraction ``depth_levels``."""


# --- Labeller ---


class PhantomLabeller:
    """Empirical-data phantom-fill labeller.

    Parameters
    ----------
    db_path : str or Path
        Path to the empirical KGHM SQLite database (relative paths are
        resolved via :func:`research_core.classes.helpers.resolve_data_path`).
    config : PhantomLabelConfig, optional
        Labelling parameters.  Defaults match the rest of the pipeline
        (tau=1s, KGHM tick=0.05 PLN, delta bounds [-0.50, 2.00]).
    hawkes : HawkesFilter / factory / bool, optional
        Hawkes filter to use.  ``True`` (default) installs the KGHM
        **single-kernel** multivariate calibration (same as
        ``MMBacktester(hawkes=True)``).  Pass :class:`HawkesFilter` or a
        zero-arg factory for full control.
    """

    def __init__(
        self,
        db_path: Union[str, Path],
        *,
        config: Optional[PhantomLabelConfig] = None,
        hawkes: Union[bool, HawkesFilter, HawkesFilterFactory] = True,
    ):
        self.db_path = resolve_data_path(db_path)
        if not self.db_path.exists():
            raise FileNotFoundError(f"Database not found: {self.db_path}")
        self.config = config or PhantomLabelConfig()
        self.n_book_levels = max(0, int(self.config.n_book_levels))
        self.n_queue_levels = max(
            self.n_book_levels, int(self.config.n_queue_levels)
        )
        self._hf_factory = resolve_filter_factory(hawkes)
        if self._hf_factory is None:
            raise ValueError(
                "hawkes must be a filter, factory, or True; phantom labelling "
                "requires the Hawkes intensity feature."
            )
        hawkes_probe_filter = self._hf_factory()
        self._n_kernels = int(hawkes_probe_filter.n_kernels)
        self.feature_names: Tuple[str, ...] = tuple(
            build_feature_names(self._n_kernels, self.n_book_levels)
        )
        self.grid_mode = str(self.config.grid_mode)
        if self.grid_mode not in ("uniform", "legal_price_ticks"):
            raise ValueError(
                "grid_mode must be 'uniform' or 'legal_price_ticks', "
                f"got {self.grid_mode!r}"
            )
        grid_step = (
            self.config.tick_size / 2.0
            if self.grid_mode == "legal_price_ticks"
            else self.config.tick_size
        )
        self.delta_grid = build_delta_grid(
            grid_step, self.config.max_delta, self.config.delta_lo,
        )
        self.n_delta = self.delta_grid.shape[0]
        self.max_candidates_per_side = (
            (self.n_delta + 1) // 2
            if self.grid_mode == "legal_price_ticks"
            else self.n_delta
        )

    # --- Public API ---

    def list_days(self) -> List[str]:
        """Return all ``day`` identifiers stored in the source DB."""
        with sqlite3.connect(str(self.db_path)) as conn:
            rows = conn.execute(
                "SELECT DISTINCT day FROM orders ORDER BY day"
            ).fetchall()
        return [r[0] for r in rows]

    def label_day(
        self,
        day_key: str,
        *,
        max_rows: Optional[int] = None,
    ) -> pd.DataFrame:
        """Produce phantom-fill labels for one trading day.

        Parameters
        ----------
        day_key : str
            Day identifier (e.g. ``"d20170111"``).
        max_rows : int, optional
            If set, stop after this many labelling timestamps.  Useful
            for smoke testing.

        Returns
        -------
        pd.DataFrame
            Rows for each candidate delta and side; columns are
            ``[t_ns, side, delta, queue_ahead] + feature_names + [label]``.
            Empty DataFrame if the day has no usable rows.
        """
        orders_df, mos_df = self._load_day(day_key)
        if orders_df.empty:
            return self._empty_frame()
        return self._label_dataframes(orders_df, mos_df, max_rows=max_rows)

    def feature_schema(self) -> dict:
        """Return the feature schema serialisable to ``feature_schema.json``.

        Encodes column → dtype + role (id / feature / target) so a
        downstream consumer can split features from metadata without
        relying on column order.
        """
        cols = {
            "t_ns":         {"dtype": "int64",   "role": "id"},
            "side":         {"dtype": "int8",    "role": "id",
                             "values": {"1": "bid", "2": "ask"}},
            "delta":        {"dtype": "float32", "role": "input",
                             "units": "PLN"},
            "queue_ahead":  {"dtype": "float32", "role": "input",
                             "units": "shares"},
        }
        for name in self.feature_names:
            cols[name] = {"dtype": "float32", "role": "feature"}
        cols["label"] = {"dtype": "uint8", "role": "target",
                         "values": {"0": "no_fill", "1": "fill"}}
        delta_grid_meta = {
            "mode": self.grid_mode,
            "lo": float(self.config.delta_lo),
            "hi": float(self.config.max_delta),
            "step": float(
                self.config.tick_size / 2.0
                if self.grid_mode == "legal_price_ticks"
                else self.config.tick_size
            ),
            "n_points": int(self.n_delta),
        }
        if self.grid_mode == "legal_price_ticks":
            delta_grid_meta.update({
                "price_tick": float(self.config.tick_size),
                "max_points_per_side": int(self.max_candidates_per_side),
                "variable_points_per_timestamp": True,
            })
        else:
            delta_grid_meta["variable_points_per_timestamp"] = False

        return {
            "tau": float(self.config.tau),
            "tick_size": float(self.config.tick_size),
            "delta_grid": delta_grid_meta,
            "phantom_size": int(self.config.phantom_size),
            "cadence": str(self.config.cadence),
            "vol_halflife": int(self.config.vol_halflife),
            "n_kernels": int(self._n_kernels),
            "n_book_levels": int(self.n_book_levels),
            "n_queue_levels": int(self.n_queue_levels),
            "n_per_t_features": len(self.feature_names),
            "columns": cols,
        }

    # --- Data loading ---

    def _load_day(self, day_key: str) -> Tuple[pd.DataFrame, pd.DataFrame]:
        want_bid = [f"bid_depth_L{i}" for i in range(self.n_queue_levels)]
        want_ask = [f"ask_depth_L{i}" for i in range(self.n_queue_levels)]
        with sqlite3.connect(str(self.db_path)) as conn:
            table_info_rows = conn.execute("PRAGMA table_info(orders)").fetchall()
            orders_table_columns = {row[1] for row in table_info_rows}
            selected_bid_depth_cols = [c for c in want_bid if c in orders_table_columns]
            selected_ask_depth_cols = [c for c in want_ask if c in orders_table_columns]
            depth_cols = ", ".join(selected_bid_depth_cols + selected_ask_depth_cols)
            base_sel = (
                "SELECT timestamp, event_type, order_id, side, order_price, "
                "volume, best_bid, best_ask, mid_price, "
                "spread_ticks, imbalance"
            )
            if depth_cols:
                orders_query = base_sel + ", " + depth_cols + " FROM orders WHERE day = ? ORDER BY timestamp"
            else:
                orders_query = base_sel + " FROM orders WHERE day = ? ORDER BY timestamp"
            orders_df = pd.read_sql_query(orders_query, conn, params=(day_key,))
            for c in want_bid + want_ask:
                if c not in orders_df.columns:
                    orders_df[c] = 0.0
            # Stable column order for downstream numpy indexing.
            orders_df = orders_df[
                [
                    "timestamp", "event_type", "order_id", "side",
                    "order_price", "volume", "best_bid", "best_ask",
                    "mid_price", "spread_ticks", "imbalance",
                ]
                + want_bid + want_ask
            ]
            if not orders_df.empty:
                orders_df["t_ns"] = (
                    pd.to_datetime(orders_df["timestamp"]).astype("int64")
                )
            mos_df = pd.read_sql_query(
                "SELECT first_time_ns AS t_ns, side AS mo_side, mo_volume "
                "FROM mo_orders WHERE day = ? ORDER BY first_time_ns",
                conn, params=(day_key,),
            )
            return orders_df, mos_df

    # --- Feature helpers ---

    def _compute_ewma_vol(self, mid: np.ndarray) -> np.ndarray:
        """EWMA of squared log-mid-returns; result aligned with ``mid``."""
        hl = max(1, int(self.config.vol_halflife))
        alpha = 1.0 - 0.5 ** (1.0 / hl)
        ewma = np.empty_like(mid, dtype=np.float64)
        valid = (mid > 0) & np.isfinite(mid)
        floor = 1e-8
        var = floor
        ewma[0] = math.sqrt(var)
        for i in range(1, len(mid)):
            if valid[i] and valid[i - 1] and mid[i - 1] > 0:
                ret = math.log(mid[i] / mid[i - 1])
                var = (1.0 - alpha) * var + alpha * ret * ret
            ewma[i] = math.sqrt(max(var, floor))
        return ewma

    def _compute_tod(self, t_ns: np.ndarray) -> np.ndarray:
        """Fraction of trading session elapsed (in [0, 1])."""
        if t_ns.size == 0:
            return np.empty(0, dtype=np.float64)
        # Convert ns since epoch to wall-clock seconds since midnight UTC,
        # then express as fraction of (session_end - session_start).  The
        # exact local-time offset doesn't matter because we only use the
        # *relative* position within the session window, anchored by the
        # first / last timestamps of the day.
        t_first = float(t_ns[0])
        t_last = float(t_ns[-1])
        span = max(1.0, t_last - t_first)
        return ((t_ns.astype(np.float64) - t_first) / span).clip(0.0, 1.0)

    # --- Event stream ---

    def _build_event_stream(
        self, orders_df: pd.DataFrame, mos_df: pd.DataFrame,
    ) -> dict:
        """Return numpy arrays for the merged orders + mo event stream.

        Output dict keys: ``t_ns``, ``kind`` (Hawkes dim 0..5), ``side``
        (1=bid, 2=ask), integer ``price_tick`` (sentinel for MOs), and
        ``volume``. Events at identical timestamps preserve relative order:
        orders before MOs within a tie, matching ``MMBacktester._replay``
        semantics.
        """
        # orders
        o_t = orders_df["t_ns"].to_numpy(dtype=np.int64)
        o_etype = orders_df["event_type"].to_numpy()
        o_side = orders_df["side"].to_numpy(dtype=np.int8)
        o_price = orders_df["order_price"].to_numpy(dtype=np.float64)
        o_vol = orders_df["volume"].to_numpy(dtype=np.float64)

        o_kind = np.empty(o_t.shape[0], dtype=np.int8)
        for i in range(o_t.shape[0]):
            try:
                o_kind[i] = classify_event(o_etype[i], int(o_side[i]))
            except ValueError:
                o_kind[i] = -1
        keep_o = o_kind >= 0
        if not keep_o.all():
            o_t = o_t[keep_o]
            o_kind = o_kind[keep_o]
            o_side = o_side[keep_o]
            o_price = o_price[keep_o]
            o_vol = o_vol[keep_o]
        o_price_tick = _prices_to_tick_indices(
            o_price, self.config.tick_size,
        )

        # mos
        if mos_df.empty:
            m_t = np.empty(0, dtype=np.int64)
            m_kind = np.empty(0, dtype=np.int8)
            m_side = np.empty(0, dtype=np.int8)
            m_price_tick = np.empty(0, dtype=np.int64)
            m_vol = np.empty(0, dtype=np.float64)
        else:
            m_t = mos_df["t_ns"].to_numpy(dtype=np.int64)
            m_mo_side = mos_df["mo_side"].to_numpy()
            m_kind = np.empty(m_t.shape[0], dtype=np.int8)
            m_side_int = np.empty(m_t.shape[0], dtype=np.int8)
            for i in range(m_t.shape[0]):
                try:
                    m_kind[i] = classify_mo(m_mo_side[i])
                except ValueError:
                    m_kind[i] = -1
                else:
                    # buy MO dim 0 -> side 1; sell MO dim 1 -> side 2.
                    m_side_int[i] = m_kind[i] + 1
            keep_m = m_kind >= 0
            if not keep_m.all():
                m_t = m_t[keep_m]
                m_kind = m_kind[keep_m]
                m_side_int = m_side_int[keep_m]
            m_side = m_side_int
            m_price_tick = np.full(
                m_t.shape[0], INVALID_PRICE_TICK, dtype=np.int64,
            )
            m_vol = mos_df["mo_volume"].to_numpy(dtype=np.float64)
            if not keep_m.all():
                m_vol = m_vol[keep_m]

        # Merge.  Stable sort by t_ns; within a tie we want order events
        # to come *before* MO events because the BBO snapshot recorded
        # on each order row reflects the post-event book state, which is
        # the right reference for any MO recorded at the same ns.
        n_o = o_t.shape[0]
        n_m = m_t.shape[0]
        ev_t = np.concatenate([o_t, m_t])
        ev_kind = np.concatenate([o_kind, m_kind])
        ev_side = np.concatenate([o_side, m_side])
        ev_price_tick = np.concatenate([o_price_tick, m_price_tick])
        ev_volume = np.concatenate([o_vol, m_vol])
        # Tag with 0 (order) / 1 (mo) for stable tie-breaking.
        ev_tag = np.concatenate([
            np.zeros(n_o, dtype=np.int8),
            np.ones(n_m, dtype=np.int8),
        ])
        order = np.lexsort((ev_tag, ev_t))
        return {
            "t_ns": ev_t[order],
            "kind": ev_kind[order],
            "side": ev_side[order],
            "price_tick": ev_price_tick[order],
            "volume": ev_volume[order],
        }

    # --- Labelling-timestamp selection ---

    def _choose_label_indices(self, orders_df: pd.DataFrame) -> np.ndarray:
        cadence = self.config.cadence
        bb = orders_df["best_bid"].to_numpy(dtype=np.float64)
        ba = orders_df["best_ask"].to_numpy(dtype=np.float64)
        valid = np.isfinite(bb) & np.isfinite(ba) & (bb > 0) & (ba > 0) & (ba > bb)

        if cadence == "every_event":
            mask = valid.copy()
        elif cadence == "bbo_change":
            mask = np.zeros(bb.shape[0], dtype=bool)
            if mask.size > 0:
                mask[0] = valid[0]
                changed = (bb[1:] != bb[:-1]) | (ba[1:] != ba[:-1])
                mask[1:] = valid[1:] & changed
        elif cadence.startswith("fixed_dt:"):
            dt_sec = float(cadence.split(":", 1)[1])
            t_ns = orders_df["t_ns"].to_numpy(dtype=np.int64)
            if t_ns.size == 0:
                mask = np.zeros(0, dtype=bool)
            else:
                target = np.arange(
                    int(t_ns[0]), int(t_ns[-1]) + 1, int(dt_sec * 1e9),
                    dtype=np.int64,
                )
                idx = np.searchsorted(t_ns, target, side="left").clip(0, t_ns.size - 1)
                mask = np.zeros(t_ns.shape[0], dtype=bool)
                mask[np.unique(idx)] = True
                mask &= valid
        else:
            raise ValueError(f"unknown cadence: {cadence!r}")
        return np.where(mask)[0]

    # --- Initial queue_ahead from snapshot depth ---

    def _initial_state(
        self,
        mid: float,
        bb: float,
        ba: float,
        bid_depth: np.ndarray,
        ask_depth: np.ndarray,
        side: int,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Phantom prices, mid-relative deltas, and initial queue ahead."""
        if self.grid_mode == "legal_price_ticks":
            return build_legal_tick_state(
                bb,
                ba,
                bid_depth,
                ask_depth,
                side,
                tick_size=self.config.tick_size,
                delta_lo=self.config.delta_lo,
                max_delta=self.config.max_delta,
            )

        tick = float(self.config.tick_size)
        eps = 1e-9
        if side == 1:
            phantom_prices = float(mid) - self.delta_grid
            cumulative_depth = np.concatenate([[0.0], np.cumsum(bid_depth)])
            ticks_from_best = (float(bb) - phantom_prices) / tick
        else:
            phantom_prices = float(mid) + self.delta_grid
            cumulative_depth = np.concatenate([[0.0], np.cumsum(ask_depth)])
            ticks_from_best = (phantom_prices - float(ba)) / tick
        level = np.floor(ticks_from_best + eps).astype(np.int64)
        queue_index = np.clip(level + 1, 0, len(cumulative_depth) - 1)
        queue = cumulative_depth[queue_index]
        return (
            phantom_prices.astype(np.float64),
            self.delta_grid.astype(np.float64),
            queue.astype(np.float64),
        )

    # --- Inner phantom replay ---

    def _replay(
        self,
        side: int,
        phantom_prices: np.ndarray,
        queue_ahead_init: np.ndarray,
        ev_kind: np.ndarray,
        ev_side: np.ndarray,
        ev_price_tick: np.ndarray,
        ev_volume: np.ndarray,
    ) -> np.ndarray:
        """Vectorised per-candidate replay; returns binary fill labels."""
        n_d = phantom_prices.shape[0]
        if self.grid_mode == "legal_price_ticks":
            phantom_price_ticks = _prices_to_tick_indices(
                phantom_prices, self.config.tick_size,
            )
        else:
            # Historical uniform candidates may be half a market tick off-grid
            # when the BBO midpoint itself lies between ticks. Comparisons in
            # tick units preserve the original float-price queue semantics.
            phantom_price_ticks = (
                np.asarray(phantom_prices, dtype=np.float64)
                / float(self.config.tick_size)
            )
        queue = queue_ahead_init.astype(np.float64, copy=True)
        labels = np.zeros(n_d, dtype=np.uint8)
        unfilled = np.ones(n_d, dtype=bool)
        phantom_size = float(self.config.phantom_size)

        if side == 1:
            opp_mo_dim = DIM_MO_SELL  # sell MO walks bids
            lo_dim = DIM_LO_BID
            cxl_dim = DIM_CXL_BID
        else:
            opp_mo_dim = DIM_MO_BUY  # buy MO walks asks
            lo_dim = DIM_LO_ASK
            cxl_dim = DIM_CXL_ASK

        for i in range(ev_kind.shape[0]):
            k = int(ev_kind[i])
            if k == opp_mo_dim:
                mo_vol = float(ev_volume[i])
                fills = unfilled & (mo_vol >= queue + phantom_size)
                if fills.any():
                    labels[fills] = 1
                    unfilled &= ~fills
                    if not unfilled.any():
                        return labels
                # Remaining unfilled: MO consumed the queue ahead (capped at 0)
                if mo_vol > 0.0:
                    queue = np.where(
                        unfilled,
                        np.maximum(queue - mo_vol, 0.0),
                        queue,
                    )
            elif k == lo_dim:
                p_tick = int(ev_price_tick[i])
                v = float(ev_volume[i])
                if v <= 0.0 or p_tick == INVALID_PRICE_TICK:
                    continue
                if side == 1:
                    ahead = unfilled & (p_tick > phantom_price_ticks)
                else:
                    ahead = unfilled & (p_tick < phantom_price_ticks)
                if ahead.any():
                    queue[ahead] += v
            elif k == cxl_dim:
                p_tick = int(ev_price_tick[i])
                v = float(ev_volume[i])
                if v <= 0.0 or p_tick == INVALID_PRICE_TICK:
                    continue
                if side == 1:
                    ahead = unfilled & (p_tick > phantom_price_ticks)
                else:
                    ahead = unfilled & (p_tick < phantom_price_ticks)
                if ahead.any():
                    queue[ahead] = np.maximum(queue[ahead] - v, 0.0)
            # Other kinds (opposite-side LO/CXL, same-direction MO) do
            # not affect our queue_ahead.
        return labels

    # --- Main loop ---

    def _label_dataframes(
        self,
        orders_df: pd.DataFrame,
        mos_df: pd.DataFrame,
        *,
        max_rows: Optional[int] = None,
    ) -> pd.DataFrame:
        stream = self._build_event_stream(orders_df, mos_df)
        ev_t_ns = stream["t_ns"]
        ev_kind = stream["kind"]
        ev_side = stream["side"]
        ev_price_tick = stream["price_tick"]
        ev_volume = stream["volume"]

        label_indices = self._choose_label_indices(orders_df)
        if max_rows is not None:
            label_indices = label_indices[:max_rows]
        if label_indices.size == 0:
            return self._empty_frame()

        t_ns_all = orders_df["t_ns"].to_numpy(dtype=np.int64)
        t0_ns = int(t_ns_all.min())
        t_sec_all = (t_ns_all - t0_ns) / 1e9
        ev_t_sec = (ev_t_ns - t0_ns) / 1e9

        bb_all = orders_df["best_bid"].to_numpy(dtype=np.float64)
        ba_all = orders_df["best_ask"].to_numpy(dtype=np.float64)
        mid_all = orders_df["mid_price"].to_numpy(dtype=np.float64)
        spread_all = orders_df["spread_ticks"].to_numpy(dtype=np.float64)
        imb_all = orders_df["imbalance"].to_numpy(dtype=np.float64)
        bid_depths = orders_df[
            [f"bid_depth_L{i}" for i in range(self.n_queue_levels)]
        ].to_numpy(dtype=np.float64)
        ask_depths = orders_df[
            [f"ask_depth_L{i}" for i in range(self.n_queue_levels)]
        ].to_numpy(dtype=np.float64)
        if str(self.config.vol_mode) == "realized_time":
            recent_vol_all = realized_vol_time_grid(
                t_sec_all, mid_all,
                window_s=self.config.vol_window_s,
                sample_dt_s=self.config.vol_sample_dt_s,
            )
        else:
            recent_vol_all = self._compute_ewma_vol(mid_all)
        tod_all = self._compute_tod(t_ns_all)

        hf = self._hf_factory()
        hf.reset(t0=0.0)
        ev_ptr = 0
        n_events = ev_t_ns.shape[0]
        tau_ns = int(self.config.tau * 1e9)

        n_rows = (
            label_indices.size * 2 * self.max_candidates_per_side
        )
        n_feat = len(self.feature_names)

        # Pre-allocate output arrays for speed.
        out_t = np.empty(n_rows, dtype=np.int64)
        out_side = np.empty(n_rows, dtype=np.int8)
        out_delta = np.empty(n_rows, dtype=np.float32)
        out_queue = np.empty(n_rows, dtype=np.float32)
        out_features = np.empty((n_rows, n_feat), dtype=np.float32)
        out_label = np.empty(n_rows, dtype=np.uint8)
        output_row = 0

        for label_row_index in label_indices:
            t_ns_lab = int(t_ns_all[label_row_index])
            t_sec_lab = float(t_sec_all[label_row_index])
            mid_lab = float(mid_all[label_row_index])
            bb_lab = float(bb_all[label_row_index])
            ba_lab = float(ba_all[label_row_index])

            # Skip degenerate rows.
            if not (math.isfinite(mid_lab) and mid_lab > 0
                    and math.isfinite(bb_lab) and math.isfinite(ba_lab)):
                continue

            # Advance Hawkes filter through all events with t < t_lab.
            # (Filter must reflect the *pre-label* state — events at
            # exactly t_lab are part of the (t, t+τ] phantom window.)
            while ev_ptr < n_events and ev_t_ns[ev_ptr] < t_ns_lab:
                k = int(ev_kind[ev_ptr])
                if k >= 0:
                    hf.update(float(ev_t_sec[ev_ptr]), k)
                ev_ptr += 1

            # Build feature vector at t_lab.
            hawkes_intensity = hf.intensity(t_sec_lab)
            feature_vector = np.empty(n_feat, dtype=np.float32)
            feature_offset = 0
            feature_vector[feature_offset:feature_offset + 6] = hawkes_intensity
            feature_offset += 6
            n_kernels = self._n_kernels
            if n_kernels > 1:
                hawkes_intensity_decomposed = hf.intensity_decomposed(t_sec_lab)
                feature_vector[feature_offset:feature_offset + n_kernels * 6] = hawkes_intensity_decomposed.ravel()
                feature_offset += n_kernels * 6
            n_book_levels = self.n_book_levels
            feature_vector[feature_offset:feature_offset + n_book_levels] = bid_depths[label_row_index, :n_book_levels]
            feature_offset += n_book_levels
            feature_vector[feature_offset:feature_offset + n_book_levels] = ask_depths[label_row_index, :n_book_levels]
            feature_offset += n_book_levels
            feature_vector[feature_offset] = spread_all[label_row_index]
            feature_offset += 1
            feature_vector[feature_offset] = imb_all[label_row_index]
            feature_offset += 1
            feature_vector[feature_offset] = recent_vol_all[label_row_index]
            feature_offset += 1
            feature_vector[feature_offset] = tod_all[label_row_index]
            feature_offset += 1
            assert feature_offset == n_feat, (feature_offset, n_feat)

            # Phantom replay window: events strictly after t_lab up to
            # and including t_lab + τ.
            i_start = int(np.searchsorted(ev_t_ns, t_ns_lab, side="right"))
            i_end = int(np.searchsorted(
                ev_t_ns, t_ns_lab + tau_ns, side="right",
            ))
            window_kind = ev_kind[i_start:i_end]
            window_side = ev_side[i_start:i_end]
            window_volume = ev_volume[i_start:i_end]

            for side_int in (1, 2):
                phantom_prices, deltas, queue_init = self._initial_state(
                    mid_lab, bb_lab, ba_lab,
                    bid_depths[label_row_index], ask_depths[label_row_index],
                    side=side_int,
                )
                n_side_candidates = phantom_prices.shape[0]
                if n_side_candidates == 0:
                    continue
                labels = self._replay(
                    side_int, phantom_prices, queue_init,
                    window_kind,
                    window_side,
                    ev_price_tick[i_start:i_end],
                    window_volume,
                )
                output_slice = slice(
                    output_row, output_row + n_side_candidates,
                )
                out_t[output_slice] = t_ns_lab
                out_side[output_slice] = side_int
                out_delta[output_slice] = deltas.astype(np.float32)
                out_queue[output_slice] = queue_init.astype(np.float32)
                out_features[output_slice, :] = feature_vector  # broadcasts to all δ rows
                out_label[output_slice] = labels
                output_row += n_side_candidates

        if output_row == 0:
            return self._empty_frame()

        # Truncate to actual filled rows (skipped degenerate rows leave gaps).
        out_t = out_t[:output_row]
        out_side = out_side[:output_row]
        out_delta = out_delta[:output_row]
        out_queue = out_queue[:output_row]
        out_features = out_features[:output_row]
        out_label = out_label[:output_row]

        cols = {
            "t_ns": out_t,
            "side": out_side,
            "delta": out_delta,
            "queue_ahead": out_queue,
        }
        for feature_index, name in enumerate(self.feature_names):
            cols[name] = out_features[:, feature_index]
        cols["label"] = out_label
        return pd.DataFrame(cols)

    # --- Empty frame template ---

    def _empty_frame(self) -> pd.DataFrame:
        dtypes = {
            "t_ns": np.int64,
            "side": np.int8,
            "delta": np.float32,
            "queue_ahead": np.float32,
        }
        for name in self.feature_names:
            dtypes[name] = np.float32
        dtypes["label"] = np.uint8
        return pd.DataFrame({c: np.empty(0, dtype=dt)
                             for c, dt in dtypes.items()})


# --- Parquet / manifest writers ---


def write_day_parquet(df: pd.DataFrame, out_path: Union[str, Path]) -> int:
    """Write ``df`` to ``out_path`` as parquet (snappy).  Returns row count.

    Parent directory is created on demand.  Existing file is overwritten.
    """
    dest = Path(out_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(dest, compression="snappy", index=False)
    return int(len(df))


def write_feature_schema(schema: dict, out_dir: Union[str, Path]) -> Path:
    """Serialise ``schema`` to ``feature_schema.json`` in ``out_dir``."""
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "feature_schema.json"
    path.write_text(json.dumps(schema, indent=2, sort_keys=False))
    return path


def write_manifest(
    out_dir: Union[str, Path],
    *,
    db_path: Union[str, Path],
    days_processed: List[str],
    config: PhantomLabelConfig,
    total_rows: int,
    runtime_seconds: float,
    git_commit: Optional[str] = None,
    hawkes_n_kernels: Optional[int] = None,
    hawkes_filter: Optional[str] = None,
) -> Path:
    """Write builder provenance to ``manifest.json``.

    Records git commit (optional), labelling parameters, list of days
    included, total row count, and wall-clock runtime so a downstream
    agent can verify exactly which dataset they are reading.
    """
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    manifest = {
        "created_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "git_commit": git_commit,
        "source_db": str(db_path),
        "config": {
            "grid_mode": str(config.grid_mode),
            "tau": float(config.tau),
            "delta_lo": float(config.delta_lo),
            "max_delta": float(config.max_delta),
            "tick_size": float(config.tick_size),
            "phantom_size": int(config.phantom_size),
            "cadence": str(config.cadence),
            "vol_mode": str(config.vol_mode),
            "vol_halflife": int(config.vol_halflife),
            "vol_window_s": float(config.vol_window_s),
            "vol_sample_dt_s": float(config.vol_sample_dt_s),
            "n_book_levels": int(config.n_book_levels),
            "n_queue_levels": int(config.n_queue_levels),
        },
        "days_processed": list(days_processed),
        "n_days": len(days_processed),
        "total_rows": int(total_rows),
        "runtime_seconds": float(runtime_seconds),
    }
    if hawkes_n_kernels is not None:
        manifest["hawkes_n_kernels"] = int(hawkes_n_kernels)
    if hawkes_filter is not None:
        manifest["hawkes_filter"] = str(hawkes_filter)
    path = directory / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2, sort_keys=False))
    return path
